spring.application.name=student-result-management
spring.datasource.url=jdbc:postgresql://localhost:5432/srms_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update